version: '2'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql-storage
    ports:
      - 6603:3306
    environment:
      MYSQL_ROOT_PASSWORD: "mypassword"
      MYSQL_USER: "shane"
      MYSQL_PASSWORD: "S13240sx91"
      MYSQL_DATABASE: "dynamic"
    volumes:
      - /storage/docker/mysql-datadir:/var/lib/mysql
    restart: always
    networks:
      - mysql_net
  ml:
    depends_on:
      - mysql
    build: .
    links:
      - mysql:mysql
    restart: always
    ports:
     - 8080
    environment:
     - SERVICE_PORTS=8080
    networks:
     - mysql_net
networks:
  mysql_net:
    driver: bridge

